steps:
- name: gcr.io/cloud-builders/go
  env: ["PROJECT_ROOT=app"]
  args: ["build", "-o", "app"]
  
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/slackbot:0.0.1", "." ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/slackbot:0.0.1', 'gcr.io/$PROJECT_ID/slackbot:latest']
 

images:
- "gcr.io/$PROJECT_ID/slackbot:0.0.1"